-- Seed: faculty (scraped from me.sogang.ac.kr 2026-08-26)
insert into faculty (name_ko,name_en,email,tel,lab_ko,lab_en,lab_url,office,field,sort_order,is_emeritus) values
('강성민','Sungmin Kang','smkang@sogang.ac.kr','02-705-8632','멀티스케일 융합기술 연구실','Multiscale Convergence Technology Laboratory','https://mctl.sogang.ac.kr','아담샬관(AS) 603호','manufacturing',10,false),
('강성원','Sungwon Kang','skang@sogang.ac.kr','02-705-7972','열유체 다중현상 연구실','Fluid and Thermal Multiphysics Laboratory','https://ftmlab.sogang.ac.kr','아담샬관(AS) 708호','thermal',20,false),
('김남근','Namkeun Kim','nkim@sogang.ac.kr','02-705-8792','응용역학 및 설계 연구실','Applied Mechanics & Design Laboratory','https://amdl.sogang.ac.kr','아담샬관(AS) 611호','design',30,false),
('김남중','Namjung Kim','namjungk@sogang.ac.kr','02-705-8633','물리 및 AI 기반 지능설계 연구실','Physics-AI Intelligent Design Laboratory','https://sites.google.com/view/namjungk','최양업관(CY) 313호','design',40,false),
('김대중','Daejoong Kim','daejoong@sogang.ac.kr','02-705-8644','에너지공학 연구실','Energy Engineering (Sogang Energy-Water Nexus) Laboratory','https://energy.sogang.ac.kr','리치과학관(R) 616호','thermal',50,false),
('김동철','Dongchoul Kim','dckim@sogang.ac.kr','02-705-8643','다중물리&다중스케일 시스템 연구실','Multiphysics & Multiscale Systems Laboratory','https://mmslab.sogang.ac.kr','아담샬관(AS) 703호','manufacturing',60,false),
('김상엽','Sang-Yup Kim','sangyupkim@sogang.ac.kr','02-705-7967','복합재료지능 연구실','Composite Intelligence Laboratory','https://composite.sogang.ac.kr','포스코 프란치스코관(F) 601호','manufacturing',70,false),
('박정열','Jungyul Park','sortpark@sogang.ac.kr','02-705-8642','나노바이오시스템 및 매니플레이션 연구실','NanoBiosystems and Manipulation Laboratory','https://nbsm.sogang.ac.kr','아담샬관(AS) 705호','control',80,false),
('손기헌','Gihun Son','gihun@sogang.ac.kr','02-705-8641','열전달(MPLab) 연구실','Multiphase Heat Transfer Laboratory','https://htlab.sogang.ac.kr','리치과학관(R) 621호','thermal',90,false),
('송지환','Jihwan Song','jsong@sogang.ac.kr','02-705-8639','지능형 융합설계 연구실','Intelligent & Convergent Design Laboratory','https://incode.sogang.ac.kr','아담샬관(AS) 613호','manufacturing',100,false),
('신충수','Choongsoo Shin','cshin@sogang.ac.kr','02-705-8825','생체역학 및 의공학 연구실','Biomechanics and Biomedical Engineering Laboratory','https://biome.sogang.ac.kr','아담샬관(AS) 608B호','design',110,false),
('이승엽','Seung-Yop Lee','sylee@sogang.ac.kr','02-705-8638','바이오모방 및 정밀기기 연구실','Biomimetics and Precision Device Laboratory','https://ispdl.sogang.ac.kr','리치과학관(R) 615호','control',120,false),
('전도영','Doyoung Jeon','dyjeon@sogang.ac.kr','02-705-8634','정밀제어 및 인간메카트로닉스 연구실','Precision Control & Human Mechatronics Laboratory','https://biomecha.sogang.ac.kr','리치과학관(R) 614호','control',130,false),
('정봉근','Bong Geun Chung','bchung@sogang.ac.kr','02-705-8823','바이오나노공학기술 연구실','BioNano Technology Laboratory','https://bntl.sogang.ac.kr','리치과학관(R) 617호','manufacturing',140,false),
('정석환','Seokhwan Jeong','seokhwan@sogang.ac.kr','02-705-7886','로봇공학 및 지능형 메커니즘 연구실','Robotics and Intelligent Mechanisms Laboratory','https://rim.sogang.ac.kr','김대건관(K) 236호','control',150,false),
('정헌재','Hunjae Jeong','hjeong@sogang.ac.kr','02-705-8636','재료설계 및 공정공학 연구실','Materials Design and Process Engineering Laboratory','https://mdpel.sogang.ac.kr','리치별관(RA) 403호','thermal',160,false),
('정현용','Hyun-Yong Jeong','jeonghy@sogang.ac.kr','02-705-8640','자동차 메카트로닉스 및 바이오역학(AM&BM) 연구실','Automotive Mechatronics & Bio Mechanics Laboratory','https://ambmlab.sogang.ac.kr','리치과학관(R) 619호','design',170,false),
('최은표','Eunpyo Choi','echoi@sogang.ac.kr','02-705-8824','지능형 바이오메디컬 마이크로유체 연구실','Intelligent Biomedical Microfluidics Laboratory','https://sites.google.com/view/choi-ibml/home','아담샬관(AS) 605호','thermal',180,false),
('김낙수','Naksoo Kim','nskim@sogang.ac.kr',NULL,'정형가공(NSMLab) 연구실','Net Shape Manufacturing Laboratory','https://nsmlab.sogang.ac.kr','떼이아르관(TE) 608호',NULL,500,true),
('이철수','Cheol-Soo Lee','cscam@sogang.ac.kr',NULL,NULL,NULL,NULL,NULL,NULL,510,true),
('이태수','Tae-Soo Lee','tslee@sogang.ac.kr',NULL,NULL,NULL,NULL,NULL,NULL,520,true),
('이형일','Hyeong-Il Lee','hylee@sogang.ac.kr',NULL,NULL,NULL,NULL,NULL,NULL,530,true),
('정시영','Si-Young Jeong','syjeong@sogang.ac.kr',NULL,NULL,NULL,NULL,NULL,NULL,540,true),
('허남건','Nahmkeon Hur','nhur@sogang.ac.kr','02-705-8637',NULL,NULL,'https://cfdlab.sogang.ac.kr',NULL,NULL,550,true);
