-- Seed: recent posts scraped from me.sogang.ac.kr (2026-08-26). Full history comes from the DB migration (see supabase/migrate_gnuboard.md)
insert into posts (board, title_ko, title_en, excerpt_ko, is_pinned, author, created_at) values
('notice','자유전공학부 기계공학 소개 자료','Introduction to Mechanical Engineering for Liberal Major students','자유전공학부 학생과 기계공학에 관심 있는 예비 공학도를 위한 기계공학 소개 자료입니다.',true,'최고관리자','2026-08-19'),
('notice','대한기계학회 기계공학 소개 자료','KSME introduction to Mechanical Engineering','대한기계학회에서 제작한 기계공학 소개 자료입니다.',true,'최고관리자','2026-08-19'),
('notice','2026-2학기 C프로그래밍(MEE1005) 개설 폐지에 따른 대체 과목 안내','Replacement course notice for C Programming (MEE1005), Fall 2026',NULL,true,'최고관리자','2026-08-10'),
('notice','기계제작실 3D 프린터 및 3D 프린터실 사용 안내','Guide to using the 3D printer room',NULL,true,'최고관리자','2026-05-29'),
('notice','2026-1학기 창의적종합설계 분반 및 수강 정원 관련 공지','Capstone Design sections and enrollment caps, Spring 2026',NULL,true,'최고관리자','2026-02-04'),
('notice','기계공학과 인지컨트롤스 장학금 대상자 선발안내','Inzi Controls Scholarship recipients announced',NULL,false,'최고관리자','2026-08-26'),
('notice','2026년 하반기 서강대-삼성전자DS 반도체Track프로그램 온라인/오프라인 설명회','Sogang–Samsung DS Semiconductor Track info session, Fall 2026',NULL,false,'최고관리자','2026-08-20'),
('notice','2026년 하반기 서강대-삼성전자DS 반도체Track프로그램 산학장학생 지원 공지','Sogang–Samsung DS Semiconductor Track scholarship application, Fall 2026',NULL,false,'최고관리자','2026-08-20'),
('notice','현대모비스 연구소 초청행사','Hyundai Mobis R&D Center invitation event',NULL,false,'최고관리자','2026-08-14'),
('research','손기헌 교수, 열/물질전달 저명 저널 "International Communications in Heat and Mass Transfer" 논문 게재','Prof. Gihun Son publishes in International Communications in Heat and Mass Transfer',NULL,false,'최고관리자','2026-08-14'),
('research','이승엽 교수, 저명 저널 Green Chemistry 표지 논문 게재','Prof. Seung-Yop Lee publishes cover article in Green Chemistry',NULL,false,'최고관리자','2026-07-16'),
('research','신충수 교수, 2026년 과학기술정보통신부 기초연구실 지원사업 선정','Prof. Choongsoo Shin selected for MSIT Basic Research Laboratory program 2026',NULL,false,'최고관리자','2026-07-14'),
('research','손기헌 교수, Applied Mathematics 분야 최고 수준 저널 ''Mathematics and Computers in Simulation'' 논문 게재','Prof. Gihun Son publishes in Mathematics and Computers in Simulation',NULL,false,'최고관리자','2026-06-30'),
('research','손기헌 교수, 열공학 분야 상위 4.7% 저널 "Applied Thermal Engineering"에 논문 게재','Prof. Gihun Son publishes in Applied Thermal Engineering (top 4.7%)',NULL,false,'최고관리자','2026-05-29'),
('research','송지환 교수 연구팀, 국제 권위지 ''Nature Communications'' 논문 게재','Prof. Jihwan Song''s team publishes in Nature Communications',NULL,false,'최고관리자','2026-05-13'),
('research','송지환 교수 연구팀, 분석 화학 분야 국제 저명 저널 ''Analytical Chemistry'' 논문 게재','Prof. Jihwan Song''s team publishes in Analytical Chemistry',NULL,false,'최고관리자','2026-05-13'),
('research','손기헌 교수 연구실, 수소에너지 분야 저명 저널 ''International Journal of Hydrogen Energy'' 논문 게재','Prof. Son''s lab publishes in International Journal of Hydrogen Energy',NULL,false,'최고관리자','2026-05-13'),
('award','박규빈 대학원생, JCK MEMS/NEMS 2026 우수 구두발표상 수상','Graduate student Gyubin Park wins Best Oral Presentation at JCK MEMS/NEMS 2026',NULL,false,'최고관리자','2026-08-03'),
('award','김도영 대학원생, ''제8회 미래형자동차 핵심기술 R&D 전문인력양성사업 성과발표회'' 우수상 수상','Graduate student Doyoung Kim wins Excellence Award at the 8th Future Vehicle R&D Showcase',NULL,false,'최고관리자','2026-07-29'),
('award','강형우 대학원생, 2026년 대통령과학장학생 선정','Graduate student Hyungwoo Kang named 2026 Presidential Science Scholar',NULL,false,'최고관리자','2026-07-29'),
('award','이준희 대학원생, 2025년 대한기계학회 본부학술대회 우수논문상 수상','Graduate student Junhee Lee wins Best Paper Award at KSME 2025 Annual Meeting',NULL,false,'최고관리자','2026-07-11'),
('award','임우석 학부생, 2025년도 추계 소음진동 학술대회 학생부문 우수논문상 수상','Undergraduate Wooseok Lim wins Best Student Paper at KSNVE Fall 2025',NULL,false,'최고관리자','2026-06-05'),
('award','박규빈 대학원생, 2026 마이크로나노시스템 춘계학술대회 우수포스터상 수상','Gyubin Park wins Best Poster at Micro/Nano Systems Spring 2026',NULL,false,'최고관리자','2026-04-07'),
('award','김도영 학부생, 2025 3D Design for the Future 최우수상 수상','Doyoung Kim wins Grand Prize at 2025 3D Design for the Future',NULL,false,'최고관리자','2025-12-29'),
('award','박규빈 대학원생, 제10회 KSME-SEMES 오픈 이노베이션챌린지 금상 수상','Gyubin Park wins Gold at the 10th KSME-SEMES Open Innovation Challenge',NULL,false,'최고관리자','2025-12-29'),
('scholarship','26년 하반기 삼성디스플레이 박사채용/박사장학생 선발','Samsung Display PhD recruitment / scholarship, Fall 2026',NULL,false,'최고관리자','2026-08-20'),
('scholarship','2026 삼성전자 DX부문 이공계 석사 채용설명회','Samsung Electronics DX Division recruitment session for MS students',NULL,false,'최고관리자','2026-08-20'),
('scholarship','코닝테크놀로지센터 경력채용 Reliability Modeling Research Engineer','Corning Technology Center: Reliability Modeling Research Engineer',NULL,false,'최고관리자','2026-07-06'),
('scholarship','GS칼텍스 2026년 상반기 신입사원 채용','GS Caltex new graduate recruitment, Spring 2026',NULL,false,'최고관리자','2026-03-19'),
('scholarship','현대자동차 3월 신입 채용','Hyundai Motor March new graduate recruitment',NULL,false,'최고관리자','2026-03-19'),
('scholarship','한화에어로스페이스 2026 상반기 대규모 신입사원 채용','Hanwha Aerospace large-scale recruitment, Spring 2026',NULL,false,'최고관리자','2026-03-19'),
('events','2026년 현대자동차 H-모빌리티 클래스 교육생 모집','Hyundai Motor H-Mobility Class 2026 recruitment',NULL,false,'최고관리자','2026-03-13'),
('events','[두산로보틱스] AI・로봇 엔지니어 양성과정(초급) 8기 모집','Doosan Robotics AI/Robot Engineer Program (Beginner) 8th cohort',NULL,false,'최고관리자','2026-01-19'),
('events','플랜트산업 전문인력 양성과정','Plant Industry Professional Training Program',NULL,false,'최고관리자','2025-05-28'),
('archive','[대학원] 논문 인센티브 신청서','[Graduate] Publication incentive application form',NULL,false,'최고관리자','2021-11-24'),
('archive','[대학원] 논문신청(proposal) 서식','[Graduate] Thesis proposal form',NULL,false,'최고관리자','2020-09-17'),
('archive','[대학원] 학위과정변경원','[Graduate] Degree program change form',NULL,false,'최고관리자','2019-08-13'),
('archive','[대학원] 학위논문 심사보고서','[Graduate] Thesis examination report',NULL,false,'최고관리자','2017-12-19'),
('major','2015.02월 졸업예정자 졸업시험 안내','Graduation exam notice for Feb 2015 graduates',NULL,false,'기계공학과','2014-11-18'),
('alumni_news','장민수 박사, 구글 ''제미나이3 해커톤 대회'' 1위 수상','Dr. Minsu Jang wins 1st place at Google Gemini 3 Hackathon',NULL,false,'최고관리자','2026-03-12'),
('alumni_news','[동문소식] 최현진 박사, 상명대학교 휴먼지능로봇공학과 조교수 임용','Dr. Hyunjin Choi appointed Assistant Professor at Sangmyung University',NULL,false,'최고관리자','2020-08-20'),
('alumni_news','[동문소식] 최정수 박사, 영남대학교 로봇기계공학과 조교수 임용','Dr. Jungsoo Choi appointed Assistant Professor at Yeungnam University',NULL,false,'최고관리자','2019-01-23'),
('alumni_news','[동문 소식] 원찬식 동문, 2022년 삼성전자 SET부문 상무 승진','Alumnus Chansik Won promoted to Vice President, Samsung Electronics SET',NULL,false,'최고관리자','2022-01-24'),
('gallery','2022 기계공학과 학술제','2022 ME Academic Festival',NULL,false,'최고관리자','2023-01-27'),
('gallery','2021 기계공학과 학술제','2021 ME Academic Festival',NULL,false,'최고관리자','2021-12-10'),
('gallery','2020 기계공학과 학술제','2020 ME Academic Festival',NULL,false,'최고관리자','2020-08-10'),
('gallery','2019 기계공학과 학술제','2019 ME Academic Festival',NULL,false,'최고관리자','2019-08-10'),
('gallery','2017학년도 전기 학위수여식','2017 Commencement',NULL,false,'최고관리자','2018-07-31'),
('gallery','2016학년도 URECA 학술제','2016 URECA Festival',NULL,false,'최고관리자','2017-03-20');

-- Sample facility reservations (August 2026, from current calendar)
insert into reservations (facility, date, start_time, end_time, user_name, status) values
('seminar','2026-08-25','13:00','18:00','손기헌 교수님','approved'),
('seminar','2026-08-26','10:30','12:00','신충수 교수님','approved'),
('seminar','2026-08-26','13:30','16:30','손기헌 교수님','approved'),
('seminar','2026-08-27','13:00','16:00','손기헌 교수님','approved'),
('seminar','2026-08-21','14:00','16:00','정석환 교수님','approved');
