export const areas = [
  { id: 'design', ko: '설계 및 재료역학', en: 'Design & Materials Mechanics', color: 'var(--sg-cardinal)',
    descKo: '기계 부품과 구조를 설계하고, 수명·안전성·신뢰도를 해석·예측하며 실험과 계산으로 검증합니다.',
    descEn: 'Designing parts and structures; analyzing and predicting durability, safety and reliability, verified by experiment and computation.',
    keywordsKo: ['생체역학', '유한요소해석', '물리·AI 기반 설계', '자동차 메카트로닉스'], keywordsEn: ['Biomechanics', 'FEA', 'Physics-AI design', 'Automotive mechatronics'] },
  { id: 'thermal', ko: '열·유체 및 에너지', en: 'Thermal, Fluids & Energy', color: 'var(--sg-orange)',
    descKo: '에너지 변환, 유동, 열전달을 탐구합니다. 이차전지·반도체 세정·데이터센터 냉각 같은 첨단 기술의 한복판에 열과 유체가 있습니다.',
    descEn: 'Energy conversion, flow and heat transfer — from batteries and semiconductor cleaning to AI data-center cooling.',
    keywordsKo: ['다상 열전달', '전산유체역학', '에너지-워터 넥서스', '마이크로유체'], keywordsEn: ['Multiphase heat transfer', 'CFD', 'Energy-water nexus', 'Microfluidics'] },
  { id: 'control', ko: '제어·진동·로보틱스', en: 'Control, Vibration & Robotics', color: 'var(--sg-blue)',
    descKo: '고속·고정밀 제어, 진동 해석과 능동 제어, 생체모방 로봇과 나노바이오 매니퓰레이션을 연구합니다.',
    descEn: 'High-speed precision control, vibration analysis and active control, biomimetic robots and nano-bio manipulation.',
    keywordsKo: ['로봇 메커니즘', '인간 메카트로닉스', '바이오모방', '나노바이오시스템'], keywordsEn: ['Robot mechanisms', 'Human mechatronics', 'Biomimetics', 'Nano-biosystems'] },
  { id: 'manufacturing', ko: '생산공학', en: 'Manufacturing Engineering', color: 'var(--sg-teal)',
    descKo: '첨단 재료의 가공과 설계, 초정밀·레이저 가공, 나노 공정과 AI 기반 공정 자동화를 다룹니다.',
    descEn: 'Advanced materials processing and design, ultra-precision and laser machining, nano-processes and AI-driven automation.',
    keywordsKo: ['복합재료', '바이오나노 공정', '다중스케일 시스템', '지능형 융합설계'], keywordsEn: ['Composites', 'Bio-nano processes', 'Multiscale systems', 'Intelligent design'] },
];
